config/routes.rb
Rails.application.routes.draw do
  get 'statuses/index'

  get 'statuses/new'

  get 'statuses/edit'

  resources :contacts

  resources :timelogs

  resources :leads

  resources :expenses

  resources :proposals

  resources :spaces

  resources :meetings

  resources :invoices

  resources :clients

  resources :tasks

  resources :projects

  get 'settings', to: 'settings#index'

  get 'dashboard', to: 'dashboard#index'

  devise_for :users, path: 'account', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: :registrations }

  resources :users, path: '/settings/users'

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'welcome#index', as: :unauthenticated_root
  end

  root to: 'dashboard#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  has_many :invoices
  has_many :expenses
  has_many :contacts
  has_many :tasks, through: :projects

  validates_presence_of :name

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  # Include gravatars for clients
  include Gravtastic
  gravtastic :email

  # Get website url
  def website_url
    unless website[/\Ahttp:\/\//] || website[/\Ahttps:\/\//]
      "http://#{website}"
    end
  end

  # Get mail to
  def mail_to
    "mailto:#{email}"
  end

  # Get google maps url
  def google_maps_url
    "http://maps.google.com/?q=#{address}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task
  belongs_to :space
  belongs_to :comment, foreign_key: :parent_id, dependent: :destroy

  has_many :comments

  validates_presence_of :title, :text, :user_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :client

	has_one :user

	validates_presence_of :first_name, :last_name

	audited
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  validates_presence_of :title, :amount

  audited
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  has_one :status

  validates_presence_of :title, :client_id

  audited
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  audited
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :users

  validates_presence_of :subject, :member_ids

  audited
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :project
  belongs_to :client

  has_many :projects, foreign_key: :parent_id, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_presence_of :name

  serialize :member_ids, Array

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  scoped_search on: [:title]

  before_save :clean_member_ids

  def clean_member_ids
    member_ids.reject! { |m| m.blank? }
    member_ids.map! { |m| m.to_i }
  end

  # Get parent
  def parent
    Project.find(parent_id) if parent_id
  end

  # Get client
  def client
    Client.find(client_id) if client_id
  end

  # Get members
  def members
    User.find(member_ids) if member_ids
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      Project.find(id).tasks.where(status_id: statuses)
    else
      Project.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    Project.find(id).tasks.where(status_id: statuses)
  end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  audited
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
	# Set default settings
	Setting['general.theme'] = 'flatly'
	Setting['general.mainbar'] = 'expanded'
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :users
  has_many :comments, dependent: :destroy

  validates_presence_of :name, :member_ids

  audited
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :task
	belongs_to :invoice

	validates_presence_of :name, :scope, :type

	scope :task, -> { where(scope: :task) }
	scope :invoice, -> { where(scope: :invoice) }
	scope :open, -> { where.not(type: :open) }
	scope :closed, -> { where(type: :closed) }
	scope :draft, -> { where(type: :draft) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  has_many :comments, dependent: :destroy
  has_one :status
  has_one :client, through: :project

  validates_presence_of :name, :project_id

  audited

  # Task status
  def status
  	Status.task.find(status_id) if status_id
  end
end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task

  validates_presence_of :time, :user_id, :task_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :projects
  has_many :comments
  has_many :timelogs
  has_many :meetings
	has_many :spaces

	validates_presence_of :email

  audited

  # Include gravatars for users
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Enable user settings
  include RailsSettings::Extend

  # Get user name
  def name
    "#{first_name} #{last_name}"
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      User.find(id).tasks.where(status_id: statuses)
    else
      User.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    User.find(id).tasks.where(status_id: statuses)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.paginate(:page => params[:page], :per_page => params[:per_page])
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:subject, :description, :start_time, :end_time)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	# Check if task assignee
	def task_assignee?(task, user)
		if task.user_id == user.id
			return true
		end

		return false
	end

	# Get task schedule status
	def task_schedule_status(task)
		status = []
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meetings/_form.html.slim
= simple_form_for(@meeting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :subject
    = f.input :description, as: :text_editor, input_html: { rows: 5 }
    = f.input :start_time, as: :datetime_picker
    = f.input :end_time, as: :datetime_picker

  .form-actions
    = f.button :submit

app/views/meetings/_grid_view.html.slim
.row.grid-view
  - @meetings.each do |meeting|
    .meeting.col-xs-12.col-md-4
      .panel.panel-default
        .panel-heading
          .panel-title
            = link_to meeting.subject, meeting

          .panel-actions.dropdown
            button.dropdown-toggle aria-expanded="false" data-toggle="dropdown" type="button"
              = icon 'chevron-down'

            ul.dropdown-menu.dropdown-right role="menu"
              li.icon-left
                = link_to icon('pencil') + 'Edit', edit_meeting_path(meeting), class: 'icon-left'
              li.icon-left
                = link_to icon('trash') + 'Delete', meeting, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icon-left'

        .panel-body data-mh="panel-body"

        .panel-footer

app/views/meetings/_list_view.html.slim
.row.list-view
  - @meetings.each do |meeting|
    .meeting.col-xs-12
      .panel.panel-default
        .panel-heading
          .panel-title
            = link_to meeting.subject, meeting

          .panel-actions.dropdown
            button.dropdown-toggle aria-expanded="false" data-toggle="dropdown" type="button"
              = icon 'chevron-down'

            ul.dropdown-menu.dropdown-right role="menu"
              li.icon-left
                = link_to icon('pencil') + 'Edit', edit_meeting_path(meeting), class: 'icon-left'
              li.icon-left
                = link_to icon('trash') + 'Delete', meeting, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icon-left'

        .panel-body

        .panel-footer
          .text-success

          .text-warning

app/views/meetings/_sidebar.html.slim
- content_for :sidebar do
	= link_to 'Add Meeting', new_meeting_path, class: 'btn btn-new'

app/views/meetings/_table_view.html.slim
table.table-listing
  thead
    tr
      th Subject
      th Start date
      th End Date
      th Description
      th Actions

  tbody
    - @meetings.each do |meeting|
      tr
        td = link_to meeting.subject, meeting
        td = meeting.start_time
        td = meeting.end_time
        td = meeting.description
        td.table-actions
          = link_to icon('pencil'), edit_meeting_path(meeting), class: 'btn btn-default'
          = link_to icon('trash'), meeting, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/meetings/edit.html.slim
= render 'common/content_header', title: 'Edit Meeting'

= render 'form'

app/views/meetings/index.html.slim
= render 'common/content_header', title: 'Meetings'

- if @meetings.any?

  - if params['view'] == 'table'
    = render 'table_view'

  - if params['view'] == 'list'
    = render 'list_view'

  - unless params['view']
    = render 'grid_view'

- else

  = render 'common/no_data'

= will_paginate @meetings

= render 'sidebar'

app/views/meetings/new.html.slim
= render 'common/content_header', title: 'New Meeting'

= render 'form'

= render 'sidebar'

app/views/meetings/show.html.slim
= render 'common/content_header', title: @meeting.subject

p
  strong Description:
  = @meeting.description
p
  strong Start time:
  = @meeting.start_time
p
  strong End time:
  = @meeting.end_time