config/routes.rb
Rails.application.routes.draw do
  get 'statuses/index'

  get 'statuses/new'

  get 'statuses/edit'

  resources :contacts

  resources :timelogs

  resources :leads

  resources :expenses

  resources :proposals

  resources :spaces

  resources :meetings

  resources :invoices

  resources :clients

  resources :tasks

  resources :projects

  get 'settings', to: 'settings#index'

  get 'dashboard', to: 'dashboard#index'

  devise_for :users, path: 'account', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: :registrations }

  resources :users, path: '/settings/users'

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'welcome#index', as: :unauthenticated_root
  end

  root to: 'dashboard#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  has_many :invoices
  has_many :expenses
  has_many :contacts
  has_many :tasks, through: :projects

  validates_presence_of :name

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  # Include gravatars for clients
  include Gravtastic
  gravtastic :email

  # Get website url
  def website_url
    unless website[/\Ahttp:\/\//] || website[/\Ahttps:\/\//]
      "http://#{website}"
    end
  end

  # Get mail to
  def mail_to
    "mailto:#{email}"
  end

  # Get google maps url
  def google_maps_url
    "http://maps.google.com/?q=#{address}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task
  belongs_to :space
  belongs_to :comment, foreign_key: :parent_id, dependent: :destroy

  has_many :comments

  validates_presence_of :title, :text, :user_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :client

	has_one :user

	validates_presence_of :first_name, :last_name

	audited
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  validates_presence_of :title, :amount

  audited
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  has_one :status

  validates_presence_of :title, :client_id

  audited
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  audited
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :users

  validates_presence_of :subject, :member_ids

  audited
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :project
  belongs_to :client

  has_many :projects, foreign_key: :parent_id, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_presence_of :name

  serialize :member_ids, Array

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  scoped_search on: [:title]

  before_save :clean_member_ids

  def clean_member_ids
    member_ids.reject! { |m| m.blank? }
    member_ids.map! { |m| m.to_i }
  end

  # Get parent
  def parent
    Project.find(parent_id) if parent_id
  end

  # Get client
  def client
    Client.find(client_id) if client_id
  end

  # Get members
  def members
    User.find(member_ids) if member_ids
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      Project.find(id).tasks.where(status_id: statuses)
    else
      Project.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    Project.find(id).tasks.where(status_id: statuses)
  end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  audited
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
	# Set default settings
	Setting['general.theme'] = 'flatly'
	Setting['general.mainbar'] = 'expanded'
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :users
  has_many :comments, dependent: :destroy

  validates_presence_of :name, :member_ids

  audited
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :task
	belongs_to :invoice

	validates_presence_of :name, :scope, :type

	scope :task, -> { where(scope: :task) }
	scope :invoice, -> { where(scope: :invoice) }
	scope :open, -> { where.not(type: :open) }
	scope :closed, -> { where(type: :closed) }
	scope :draft, -> { where(type: :draft) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  has_many :comments, dependent: :destroy
  has_one :status
  has_one :client, through: :project

  validates_presence_of :name, :project_id

  audited

  # Task status
  def status
  	Status.task.find(status_id) if status_id
  end
end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task

  validates_presence_of :time, :user_id, :task_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :projects
  has_many :comments
  has_many :timelogs
  has_many :meetings
	has_many :spaces

	validates_presence_of :email

  audited

  # Include gravatars for users
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Enable user settings
  include RailsSettings::Extend

  # Get user name
  def name
    "#{first_name} #{last_name}"
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      User.find(id).tasks.where(status_id: statuses)
    else
      User.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    User.find(id).tasks.where(status_id: statuses)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.paginate(:page => params[:page], :per_page => params[:per_page])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :project_id, :user_id, :start_date, :due_date, :est_hours, :log_hours, :completed, :description)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	# Check if task assignee
	def task_assignee?(task, user)
		if task.user_id == user.id
			return true
		end

		return false
	end

	# Get task schedule status
	def task_schedule_status(task)
		status = []
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tasks/_box_footer.html.slim
.box-footer
  .row
    .col-xs-4.border-right
      .description-block
        h5.description-header.text-aqua
          - if task.est_hours
            = task.est_hours
          - else
            = 0
        span.desctiption-text
          = 'Est. Hours'

    .col-xs-4.border-right
      .description-block
        h5.description-header.text-green
          - if task.log_hours
            = task.log_hours
          - else
            = 0
        span.desctiption-text
          = 'Hours Spent'

    .col-xs-4
      .description-block
        h5.description-header.text-muted
          = task.comments.count
        span.desctiption-text
          = 'Comments'

app/views/tasks/_box_header.html.slim
.box-header
  .box-title
    - if task_assignee?(task, current_user)
      span.text-yellow.icon-left
        = icon 'star'

    = link_to task.name, task

  .box-tools.pull-right
    button.btn.btn-box-tool.dropdown-toggle aria-expanded="false" data-toggle="dropdown" type="button"
      = icon 'bars'

    ul.dropdown-menu.dropdown-right role="menu"
      li
        = link_to 'Edit', edit_task_path(task)
      li
        = link_to 'Delete', task, data: { confirm: 'Are you sure?' }, method: :delete

app/views/tasks/_form.html.slim
- statuses = Status.where(model: :task)

= simple_form_for(@task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :project, prompt: '--'
    = f.input :description, as: :text_editor, input_html: { rows: 5 }
    = f.association :user, label_method: :name, label: 'Assigned to', include_blank: '--'
    = f.input :status_id, collection: statuses, default: statuses.first
    = f.input :start_date, as: :date_picker
    = f.input :due_date, as: :date_picker
    = f.input :est_hours, label: 'Estimated hours'
    = f.input :log_hours, label: 'Log hours'
    = f.input :completed, collection: percentage_select, default: 0

  .form-actions
    = f.button :submit

app/views/tasks/_grid_view.html.slim
.row.grid-view
  - @tasks.each do |task|
    .task-item.col-xs-12.col-md-4
      .box.box-card class=('box-' + status_color(task.status))
        = render 'box_header', task: task

        .flat-body
          .row
            .col-xs-6.border-right
              .description-block
                h2.text-green.desctiption-text
                  strong
                    = 'ON'
                span.desctiption-text
                  = 'Schedule'

            .col-xs-6
              .description-block
                h2.desctiption-text class=('text-' + ratio_color(task.completed))
                  strong
                    = task.completed.to_s + '%'
                span.desctiption-text
                  = 'Completed'

        .box-group
          .box-group-item.col-xs-12
            p.notes
              - unless task.description.blank?
                = task.description.html_safe
              - else
                = 'No task description'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Project' + ': '
            - if task.project
              = link_to task.project.name, task.project
            - else
              = 'No project set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Assignee' + ': '
            - if task.user
              = gravatar task.user, 16, class: 'img-circle'
              = link_to task.user.name, task.user
            - else
              = 'No user assigned'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Start' + ': '
            - if task.start_date
              = task.start_date.strftime('%d %B %Y')
            - else
              = 'No start date set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Due' + ': '
            - if task.due_date
              = task.due_date.strftime('%d %B %Y')
            - else
              = 'No due date set'

        = render 'box_footer', task: task

app/views/tasks/_list_view.html.slim
.row.list-view
  - @tasks.each do |task|
    .task-item.col-xs-12
      .box.box-card.clearfix class=('box-' + status_color(task.status))
        = render 'box_header', task: task

        .box-body.col-xs-12.col-md-3.border-top
          .row
            .col-xs-6.border-right
              .description-block
                h3.text-green.desctiption-text
                  strong
                    = 'ON'
                span.desctiption-text
                  = 'Schedule'

            .col-xs-6
              .description-block
                h3.desctiption-text class=('text-' + ratio_color(task.completed))
                  strong
                    = task.completed.to_s + '%'
                span.desctiption-text
                  = 'Completed'

        .box-group.col-xs-12.col-md-5.no-padding.border-right.border-left
          .box-group-item.col-xs-12
            p.notes
              - unless task.description.blank?
                = task.description.html_safe
              - else
                = 'No task description'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Project' + ': '
            - if task.project
              = link_to task.project.name, task.project
            - else
              = 'No project set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Assignee' + ': '
            - if task.user
              = gravatar task.user, 16, class: 'img-circle'
              = link_to task.user.name, task.user
            - else
              = 'No user assigned'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Start' + ': '
            - if task.start_date
              = task.start_date.strftime('%d %B %Y')
            - else
              = 'No start date set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Due' + ': '
            - if task.due_date
              = task.due_date.strftime('%d %B %Y')
            - else
              = 'No due date set'

        .col-xs-12.col-md-4.no-padding
          = render 'box_footer', task: task

app/views/tasks/_sidebar.html.slim
- content_for :sidebar do

app/views/tasks/edit.html.slim
= render 'common/content_header', title: 'Edit task'

= render 'form'

app/views/tasks/index.html.slim
= render 'common/content_header', title: 'Tasks'

- if @tasks.any?

  - if params['view'] == 'list'
  	= render 'list_view'
  - else
    = render 'grid_view'

- else

  = render 'common/no_data'

= will_paginate @tasks

app/views/tasks/new.html.slim
= render 'common/content_header', title: 'New task'

= render 'form'

= render 'sidebar'

app/views/tasks/show.html.slim
= render 'common/content_header', title: @task.name
p
  strong Project:
  - if @task.project_id
    = Project.find(@task.project_id).name

p
  strong Assigned to:
  - if @task.user_id
    = User.find(@task.user_id).name

p
  strong Start date:
  = @task.start_date

p
  strong Due date:
  = @task.due_date

p
  strong Estimated hours:
  = @task.est_hours

p
  strong Description:
  = @task.description