config/routes.rb
Rails.application.routes.draw do
  get 'statuses/index'

  get 'statuses/new'

  get 'statuses/edit'

  resources :contacts

  resources :timelogs

  resources :leads

  resources :expenses

  resources :proposals

  resources :spaces

  resources :meetings

  resources :invoices

  resources :clients

  resources :tasks

  resources :projects

  get 'settings', to: 'settings#index'

  get 'dashboard', to: 'dashboard#index'

  devise_for :users, path: 'account', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: :registrations }

  resources :users, path: '/settings/users'

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'welcome#index', as: :unauthenticated_root
  end

  root to: 'dashboard#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  has_many :invoices
  has_many :expenses
  has_many :contacts
  has_many :tasks, through: :projects

  validates_presence_of :name

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  # Include gravatars for clients
  include Gravtastic
  gravtastic :email

  # Get website url
  def website_url
    unless website[/\Ahttp:\/\//] || website[/\Ahttps:\/\//]
      "http://#{website}"
    end
  end

  # Get mail to
  def mail_to
    "mailto:#{email}"
  end

  # Get google maps url
  def google_maps_url
    "http://maps.google.com/?q=#{address}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task
  belongs_to :space
  belongs_to :comment, foreign_key: :parent_id, dependent: :destroy

  has_many :comments

  validates_presence_of :title, :text, :user_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :client

	has_one :user

	validates_presence_of :first_name, :last_name

	audited
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  validates_presence_of :title, :amount

  audited
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :project

  has_one :status

  validates_presence_of :title, :client_id

  audited
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  audited
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :users

  validates_presence_of :subject, :member_ids

  audited
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :project
  belongs_to :client

  has_many :projects, foreign_key: :parent_id, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_presence_of :name

  serialize :member_ids, Array

  audited

  extend FriendlyId
  friendly_id :name, use: :slugged

  scoped_search on: [:title]

  before_save :clean_member_ids

  def clean_member_ids
    member_ids.reject! { |m| m.blank? }
    member_ids.map! { |m| m.to_i }
  end

  # Get parent
  def parent
    Project.find(parent_id) if parent_id
  end

  # Get client
  def client
    Client.find(client_id) if client_id
  end

  # Get members
  def members
    User.find(member_ids) if member_ids
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      Project.find(id).tasks.where(status_id: statuses)
    else
      Project.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    Project.find(id).tasks.where(status_id: statuses)
  end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  audited
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
	# Set default settings
	Setting['general.theme'] = 'flatly'
	Setting['general.mainbar'] = 'expanded'
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :users
  has_many :comments, dependent: :destroy

  validates_presence_of :name, :member_ids

  audited
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :task
	belongs_to :invoice

	validates_presence_of :name, :scope, :type

	scope :task, -> { where(scope: :task) }
	scope :invoice, -> { where(scope: :invoice) }
	scope :open, -> { where.not(type: :open) }
	scope :closed, -> { where(type: :closed) }
	scope :draft, -> { where(type: :draft) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  has_many :comments, dependent: :destroy
  has_one :status
  has_one :client, through: :project

  validates_presence_of :name, :project_id

  audited

  # Task status
  def status
  	Status.task.find(status_id) if status_id
  end
end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task

  validates_presence_of :time, :user_id, :task_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :projects
  has_many :comments
  has_many :timelogs
  has_many :meetings
	has_many :spaces

	validates_presence_of :email

  audited

  # Include gravatars for users
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Enable user settings
  include RailsSettings::Extend

  # Get user name
  def name
    "#{first_name} #{last_name}"
  end

  # Open tasks
  def open_tasks
    statuses = Status.task.open.ids
    unless statuses.empty?
      User.find(id).tasks.where(status_id: statuses)
    else
      User.find(id).tasks
    end
  end

  # Closed tasks
  def closed_tasks
    statuses = Status.task.closed.ids
    User.find(id).tasks.where(status_id: statuses)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => params[:per_page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :parent_id, :client_id, :start_date, :due_date, :description, :member_ids => [])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	# Check if project member
	def project_member?(project, user)
		if project.member_ids.include?(user.id)
			return true
		end

		return false
	end

	# Get project complete ratio
	def project_complete_ratio(project)
		total = 0

		unless project.tasks.empty?
			tasks = project.tasks.count
			ratio = project.tasks.sum(:completed)
			total = ratio / tasks
		end

		return total
	end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	# Check if task assignee
	def task_assignee?(task, user)
		if task.user_id == user.id
			return true
		end

		return false
	end

	# Get task schedule status
	def task_schedule_status(task)
		status = []
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/_box_footer.html.slim
.box-footer
  .row
    .col-xs-4.border-right
      .description-block
        h5.description-header.text-green
          = project.open_tasks.count
        span.desctiption-text
          = 'Open Tasks'

    .col-xs-4.border-right
      .description-block
        h5.description-header.text-red
          = project.closed_tasks.count
        span.desctiption-text
          = 'Closed Tasks'

    .col-xs-4
      .description-block
        h5.description-header.text-blue
          = project.members.count
        span.desctiption-text
          = 'Members'

app/views/projects/_box_header.html.slim
.box-header
  .box-title
    - if project_member?(project, current_user)
      span.text-yellow.icon-left
        = icon 'star'

    = link_to project.name, project

  .box-tools.pull-right
    button.btn.btn-box-tool.dropdown-toggle aria-expanded="false" data-toggle="dropdown" type="button"
      = icon 'bars'

    ul.dropdown-menu.dropdown-right role="menu"
      li
        = link_to 'Edit', edit_project_path(project)
      li
        = link_to 'Delete', project, data: { confirm: 'Are you sure?' }, method: :delete

app/views/projects/_form.html.slim
- users = User.all
- projects = Project.where.not(id: @project.id)

= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description, as: :text_editor, input_html: { rows: 5 }
    = f.input :parent_id, collection: projects, include_blank: '--', label: 'Parent project'
    = f.association :client, prompt: '--'
    = f.input :start_date, as: :date_picker
    = f.input :due_date, as: :date_picker
    = f.input :member_ids, as: :check_boxes, collection: users, label_method: :name, value_method: :id, label: 'Members', default: current_user.id

  .form-actions
    = f.button :submit

app/views/projects/_grid_view.html.slim
.row.grid-view
  - @projects.each do |project|
    .project-item.col-xs-12.col-md-6.col-lg-4
      .box.box-card
        = render 'box_header', project: project

        .flat-body
          .row
            .col-xs-6.border-right
              .description-block
                h2.text-green.desctiption-text
                  strong
                    = 'ON'
                span.desctiption-text
                  = 'Schedule'

            .col-xs-6
              .description-block
                h2.desctiption-text class=('text-' + ratio_color(project_complete_ratio(project)))
                  strong
                    = project_complete_ratio(project).to_s + '%'
                span.desctiption-text
                  = 'Completed'

        .box-group
          .box-group-item.col-xs-12
            p.notes
              - unless project.description.blank?
                = project.description.html_safe
              - else
                = 'No project description'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Client' + ': '
            - if project.client
              = link_to project.client.name, project.client
            - else
              = 'No client set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Parent' + ': '
            - if project.parent
              = link_to project.parent.name, project.parent
            - else
              = 'No parent project'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Start' + ': '
            - if project.start_date
              = project.start_date.strftime('%d %B %Y')
            - else
              = 'No start date set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Due' + ': '
            - if project.due_date
              = project.due_date.strftime('%d %B %Y')
            - else
              = 'No due date set'

        = render 'box_footer', project: project

app/views/projects/_list_view.html.slim
.row.list-view
  - @projects.each do |project|
    .project-item.col-xs-12
      .box.box-card.clearfix
        = render 'box_header', project: project

        .box-body.col-xs-12.col-md-3.border-top
          .row
            .col-xs-6.border-right
              .description-block
                h3.text-green.desctiption-text
                  strong
                    = 'ON'
                span.desctiption-text
                  = 'Schedule'

            .col-xs-6
              .description-block
                h3.desctiption-text class=('text-' + ratio_color(project_complete_ratio(project)))
                  strong
                    = project_complete_ratio(project).to_s + '%'
                span.desctiption-text
                  = 'Completed'

        .box-group.col-xs-12.col-md-5.no-padding.border-right.border-left
          .box-group-item.col-xs-12
            p.notes
              - unless project.description.blank?
                = project.description.html_safe
              - else
                = 'No project description'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Client' + ': '
            - if project.client
              = link_to project.client.name, project.client
            - else
              = 'No client set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Parent' + ': '
            - if project.parent
              = link_to project.parent.name, project.parent
            - else
              = 'No parent project'

          .box-group-item.col-xs-12.col-md-6.border-right
            strong
              = 'Start' + ': '
            - if project.start_date
              = project.start_date.strftime('%d %B %Y')
            - else
              = 'No start date set'

          .box-group-item.col-xs-12.col-md-6
            strong
              = 'Due' + ': '
            - if project.due_date
              = project.due_date.strftime('%d %B %Y')
            - else
              = 'No due date set'

        .col-xs-12.col-md-4.no-padding
          = render 'box_footer', project: project

app/views/projects/_sidebar.html.slim
- content_for :sidebar do

  ul.sidebar-menu
    li.header
      = 'SORT BY'
    li
      = link_to 'Client Name', params.merge(sort_by: 'client_name')
    li
      = link_to 'Start Date', params.merge(sort_by: 'start_date')
    li
      = link_to 'Due Date', params.merge(sort_by: 'due_date')

app/views/projects/edit.html.slim
= render 'common/content_header', title: 'Edit project'

= render 'form'

app/views/projects/index.html.slim
= render 'common/content_header', title: 'Projects'

- if @projects.any?

  - if params['view'] == 'list'
  	= render 'list_view'
  - else
    = render 'grid_view'

- else

  = render 'common/no_data'

= will_paginate @projects

= render 'sidebar'

app/views/projects/new.html.slim
= render 'common/content_header', title: 'New project'

= render 'form'

= render 'sidebar'

app/views/projects/show.html.slim
= render 'common/content_header', title: @project.name

.panel.panel-default
  .panel-heading
    h3.panel-title = 'Project information'

  .panel-body
    p
      strong Client:
      = @project.client.name

    p
      strong Parent:
      - if @project.parent
        = @project.parent.name

    p
      strong Start date:
      = @project.start_date
    p
      strong Due date:
      = @project.due_date
    p
      strong Description:
      = @project.description.html_safe
    p
      strong Members:
      - unless @project.members.empty?
        - @project.members.each do |m|
          = m.name

.panel.panel-default
  .panel-heading
    h3.panel-title = 'Activity'

  ul.list-group
    - @project.audits.last(5).each do |a|
      li.list-group-item
        = gravatar a.user, 24
        = a.user.name
        = a.action
        = a.audited_changes